services:
  subatic-transcoder:
    image: ghcr.io/orthdron/subatic-transcoder:latest
    container_name: subatic-transcoder
    environment:
      - SQS_ENABLED=false
      - SQS_URL=YOUR_SQS_URL
      
      # Download bucket configuration
      - DOWNLOAD_S3_ENDPOINT=http://localhost:9000
      - DOWNLOAD_S3_ACCESS_KEY_ID=YOUR_DOWNLOAD_S3_ACCESS_KEY_ID
      - DOWNLOAD_S3_SECRET_ACCESS_KEY=YOUR_DOWNLOAD_S3_SECRET_ACCESS_KEY
      - DOWNLOAD_S3_REGION=YOUR_DOWNLOAD_S3_REGION
      - DOWNLOAD_S3_BUCKET=YOUR_DOWNLOAD_BUCKET_NAME
      
      # Upload bucket configuration: Can be the same as download if public
      - UPLOAD_S3_ACCESS_KEY_ID=YOUR_UPLOAD_S3_ACCESS_KEY_ID
      - UPLOAD_S3_SECRET_ACCESS_KEY=YOUR_UPLOAD_S3_SECRET_ACCESS_KEY
      - UPLOAD_S3_REGION=YOUR_UPLOAD_S3_REGION
      - UPLOAD_S3_BUCKET=YOUR_UPLOAD_BUCKET_NAME
      - UPLOAD_S3_ENDPOINT=YOUR_UPLOAD_S3_ENDPOINT
      
      # Webhook configuration
      - WEBHOOK_URL=http://localhost:3000/
      - WEBHOOK_TOKEN=YOUR_WEBHOOK_TOKEN
    restart: unless-stopped