services:
  subatic-transcoder:
    image: ghcr.io/orthdron/subatic-transcoder:latest
    container_name: subatic-transcoder
    environment:
      - SQS_ENABLED=false
      - SQS_URL=YOUR_SQS_URL

      # Download bucket configuration
      - RAWFILES_S3_ENDPOINT=http://localhost:9000
      - RAWFILES_S3_ACCESS_KEY_ID=YOUR_RAWFILES_S3_ACCESS_KEY_ID
      - RAWFILES_S3_SECRET_ACCESS_KEY=YOUR_RAWFILES_S3_SECRET_ACCESS_KEY
      - RAWFILES_S3_REGION=YOUR_RAWFILES_S3_REGION
      - RAWFILES_S3_BUCKET=YOUR_RAWFILES_BUCKET_NAME

      # Upload bucket configuration: Can be the same as download if public
      - PROCESSED_S3_ACCESS_KEY_ID=YOUR_PROCESSED_S3_ACCESS_KEY_ID
      - PROCESSED_S3_SECRET_ACCESS_KEY=YOUR_PROCESSED_S3_SECRET_ACCESS_KEY
      - PROCESSED_S3_REGION=YOUR_PROCESSED_S3_REGION
      - PROCESSED_S3_BUCKET=YOUR_PROCESSED_BUCKET_NAME
      - PROCESSED_S3_ENDPOINT=YOUR_PROCESSED_S3_ENDPOINT

      # Webhook configuration
      - WEBHOOK_URL=http://localhost:3000/
      - WEBHOOK_TOKEN=YOUR_WEBHOOK_TOKEN
    restart: unless-stopped
